# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/hdd/files/Dropbox/Personal/Python/survtur_glacier/src/survtur_glacier/qts/tierdialog_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TierDialog(object):
    def setupUi(self, TierDialog):
        TierDialog.setObjectName("TierDialog")
        TierDialog.resize(262, 275)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TierDialog.sizePolicy().hasHeightForWidth())
        TierDialog.setSizePolicy(sizePolicy)
        TierDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TierDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(TierDialog)
        self.label.setAutoFillBackground(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.formLayout_3.setHorizontalSpacing(12)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(TierDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.btnPickFolder = QtWidgets.QPushButton(TierDialog)
        self.btnPickFolder.setObjectName("btnPickFolder")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnPickFolder)
        self.label_3 = QtWidgets.QLabel(TierDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.bultRadio = QtWidgets.QRadioButton(TierDialog)
        self.bultRadio.setObjectName("bultRadio")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bultRadio)
        self.standardRadio = QtWidgets.QRadioButton(TierDialog)
        self.standardRadio.setObjectName("standardRadio")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.standardRadio)
        self.expeditedRadiio = QtWidgets.QRadioButton(TierDialog)
        self.expeditedRadiio.setObjectName("expeditedRadiio")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.expeditedRadiio)
        self.verticalLayout.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(TierDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOk = QtWidgets.QPushButton(TierDialog)
        self.btnOk.setEnabled(False)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TierDialog)
        self.btnOk.clicked.connect(TierDialog.accept) # type: ignore
        self.btnCancel.clicked.connect(TierDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TierDialog)

    def retranslateUi(self, TierDialog):
        _translate = QtCore.QCoreApplication.translate
        TierDialog.setWindowTitle(_translate("TierDialog", "Select tier"))
        self.label.setText(_translate("TierDialog", "[will be rewritten]"))
        self.label_2.setText(_translate("TierDialog", "Save to"))
        self.btnPickFolder.setText(_translate("TierDialog", "Select folder..."))
        self.label_3.setText(_translate("TierDialog", "Tier"))
        self.bultRadio.setText(_translate("TierDialog", "Bulk $ (5-12 hours)"))
        self.standardRadio.setText(_translate("TierDialog", "Standard $$ (3-5 hours)"))
        self.expeditedRadiio.setText(_translate("TierDialog", "Expedited $$$ (few minutes)"))
        self.btnCancel.setText(_translate("TierDialog", "Cancel"))
        self.btnOk.setText(_translate("TierDialog", "OK"))
